version: "3.8"

services:

  director:

    # building block
    build:
      context: .
      dockerfile: docker/Dockerfile

    # other configuration

    # NOTE the network_mode host, does not allow this container to link to others and therefore communicate
    # with them by calling them through their "container name"
    #network_mode: host


    stdin_open: true # docker run -i
    tty: true # docker run -t

    # dependencies
    env_file:
      - env/.env

    # add links between the containers
    depends_on:
      - postgres

    links:
      - postgres:5432

  postgres:
    image: postgres:latest
    env_file:
      - env/.env.db
    volumes:
      - postgres_data:/var/lib/postgres/data/

volumes:
  postgres_data:
