version: "3.8"

services:

  director:
    # building block
    build:
      context: .
      dockerfile: docker/Dockerfile

    # other configuration
    stdin_open: true # docker -i
    tty: true # docker -t

    # dependencies
    env_file:
      - env/.env

    # add links between the containers
    depends_on:
      - postgres

    networks:
      - adversary
      - default
      #- master

  postgres:
    image: postgres:latest
    env_file:
      - env/.env.db
    volumes:
      - postgres_data:/var/lib/postgres/data/
    networks:
      - adversary

  msf:
    image: metasploitframework/metasploit-framework
    ports:
      - 55553:55553
    volumes:
      - ./src/data/msf:/home/msf/.msf4/
    env_file:
      - env/.env.msf
    networks:
      - adversary
      - default
    stdin_open: true
    tty: true
    command:
      - "./msfconsole"
      - "-r"
      - "docker/msfconsole.rc"
      - "-y"
      - "$APP_HOME/config/database.yml"
      - "-x"
      - "load msgrpc ServerHost=$$MSFRPC_HOST ServerPort=$$MSFRPC_PORT User=$$MSFRPC_USER Pass=$$MSFRPC_PASSWORD"

volumes:
  postgres_data:

networks:
  default:
  adversary:
    # This network is meant to be used in bridge mode between (default) between all the containers with access to it
    # In this network we will only have
    name: adversary
    # driver: bridge
  #--------------#
  #master:
    # Use this network to communicate/send messages between the adversary and the game-master through the Bus
    #external:
      #name: master
