version: "3.8"

services:

  director:
    # building block
    build:
      context: .
      dockerfile: docker/Dockerfile

    # other configuration
    stdin_open: true # docker -i
    tty: true # docker -t

    # dependencies
    env_file:
      - env/.env

    # add links between the containers
    depends_on:
      - postgres

    volumes:
      - ./src/tools/logs:/usr/src/app/tools/logs

    networks:
      - adversary
      - defenders
      - master

  postgres:
    image: postgres:latest
    env_file:
      - env/.env.db
    volumes:
      - postgres_data:/var/lib/postgres/data/
    networks:
      - adversary

  msf:
    image: metasploitframework/metasploit-framework
    tty: true
    stdin_open: true
    privileged: true
    ports:
      - 55553:55553
    # This command included: -S
    #./msfconsole -r docker/msfconsole.rc -y $APP_HOME/config/database.yml -x load msgrpc ServerHost=0.0.0.0 ServerPort=55553 User=username Pass=password exit
    # ./msfrpcd -a 0.0.0.0 -p 55553 -U username -P password -f
    command: ./msfrpcd -a ${MSFRPC_HOST-0.0.0.0} -p ${MSFRPC_PORT-55553} -U ${MSFRPC_USER-username} -P ${MSFRPC_PASSWORD-password} -f
    volumes:
      - ./src/data/msf:/home/msf/.msf4/
    env_file:
      - env/.env.msf
    networks:
      defenders:
        ipv4_address: 10.5.0.7
      adversary:

volumes:
  postgres_data:

networks:
  default:
  adversary:
    # This network is meant to be used in bridge mode between (default) between all the containers with access to it
    # In this network we will only have
    name: adversary
    # driver: bridge
  #--------------#
  # defenders external network containing the targets
  defenders:
    external:
      name: defenders
  #--------------#
  master:
    # Use this network to communicate/send messages between the adversary and the game-master through the Bus
    external:
      name: master
