version: "3.7"

services:

  target1:
    image: citizenstig/dvwa # dvwa
    environment:
      - MYSQL_PASS="insecure123"
    # ports:
    #   - 8081:80
    #   - 8031:3306
    healthcheck:
      test: "curl -f localhost:80"
      interval: 5s
      retries: 3
      start_period: "10"
    networks:
      - defenders
      # this is just for debugging
      # TODO remove this access
      - master

  target2:
    image: hmlio/vaas-cve-2014-6271 # shellshock
    # ports:
    #   - 8082:80
    healthcheck:
      test: "curl -f localhost:80"
      interval: 5s
      retries: 3
    networks:
      - defenders

  target3:
    image: penkit/vsftpd:2.3.4 # vsftpd backdoor, do not trust this image
    networks:
      - defenders

  wordpress:
    image: vulhub/wordpress:4.6
    depends_on:
     - wordpress-mysql
    environment: 
     - WORDPRESS_DB_HOST=wordpress-mysql:3306
     - WORDPRESS_DB_USER=root
     - WORDPRESS_DB_PASSWORD=root
     - WORDPRESS_DB_NAME=wordpress
    ports:
     - "8080:80"

    networks:
      defenders:
        ipv4_address: 10.5.0.6

  wordpress-mysql:
    image: mysql:5
    environment: 
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=wordpress
    networks:
      - defenders

networks:
  # use this network to define the targets that will be in the network
  defenders:
    name: defenders
    # this network connects all the devices together
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          # gateway: 10.5.0.1

  master:
    name: master
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          # gateway: 10.6.0.1
