version: "3.7"

services:

  director:
    build: src
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      MSFRPC_HOSTS: "localhost:55553"
      LOGLEVEL: 'DEBUG'
      SPEED: 80
