version: "3.7"

services:

  director:
    # building block
    build:
      context: .
      dockerfile: docker/Dockerfile

    # other configuration
    stdin_open: true # docker -i
    tty: true # docker -t

    # dependencies
    env_file:
      - env/.env

    # add links between the containers
    depends_on:
      - postgres

    networks:
      - adversary
      - default
      #- master

  postgres:
    image: postgres:latest
    env_file:
      - env/.env.db
    volumes:
      - postgres_data:/var/lib/postgres/data/
    networks:
      - adversary

  msf:
    image: metasploitframework/metasploit-framework
    ports:
      - 55553:55553
    # This command included: -S
    command: ./msfrpcd -a 0.0.0.0 -p 55553 -U username -P password -f
    volumes:
      - ./src/data/msf:/home/msf/.msf4/
    env_file:
      - env/.env.msf
    networks:
      - adversary
      - default

volumes:
  postgres_data:

networks:
  default:
  adversary:
    # This network is meant to be used in bridge mode between (default) between all the containers with access to it
    # In this network we will only have
    name: adversary
    # driver: bridge
  #--------------#
  #master:
    # Use this network to communicate/send messages between the adversary and the game-master through the Bus
    #external:
      #name: master
