version: "3.7"

services:

  target1:
    image: citizenstig/dvwa # dvwa
    environment:
      - MYSQL_PASS="insecure123"
    # ports:
    #   - 8081:80
    #   - 8031:3306
    healthcheck:
      test: "curl -f localhost:80"
      interval: 5s
      retries: 3
      start_period: "10"
    networks:
      - defenders

  target2:
    image: hmlio/vaas-cve-2014-6271 # shellshock
    # ports:
    #   - 8082:80
    healthcheck:
      test: "curl -f localhost:80"
      interval: 5s
      retries: 3
    networks:
      - defenders

  target3:
    image: penkit/vsftpd:2.3.4 # vsftpd backdoor, do not trust this image
    networks:
      - defenders

  wordpress:
    image: vulhub/wordpress:4.6
    depends_on:
     - wordpress-mysql
    environment: 
     - WORDPRESS_DB_HOST=wordpress-mysql:3306
     - WORDPRESS_DB_USER=root
     - WORDPRESS_DB_PASSWORD=root
     - WORDPRESS_DB_NAME=wordpress
    ports:
     - "8080:80"
    links:
      - wordpress-mysql
    # unix/webapp/wp_phpmailer_host_header
    # set RHOSTS wordpress
    # cat /var/www/html/wp-config.php
    # fail: execute -f /bin/grep -a DB_PASSWORD /var/www/html/wp-config.php

    networks:
      - defenders


  wordpress-mysql:
    image: mysql:5
    environment: 
     - MYSQL_ROOT_PASSWORD=root
    networks:
      - defenders

networks:
  defenders:
    name: defenders