version: "3.7"

services:

  msf:
    image: metasploitframework/metasploit-framework
    stdin_open: true
    tty: true
    ports:
      - 55553:55553
    environment: 
      DATABASE_URL: postgres://msf:msfdbu123@db:5432/msfdb
      MSF_UID: 1201
      MSF_GID: 1201
    command:
      - "./msfconsole"
      - "-r"
      - "docker/msfconsole.rc"
      - "-y"
      - "$APP_HOME/config/database.yml"
      - "-x"
      - "load msgrpc ServerHost=0.0.0.0 ServerPort=55553 User=director Pass=directorU123"
    volumes:
      - ./data/msf:/home/msf/.msf4
    links:
      - target1
      - target2
      - target3
      - wordpress
    depends_on:
      - target1
      - target2
      - target3

  target1:
    image: citizenstig/dvwa # dvwa
    environment:
      - MYSQL_PASS="insecure123"
    # ports:
    #   - 8081:80
    #   - 8031:3306
    healthcheck:
      test: "curl -f localhost:80"
      interval: 5s
      retries: 3
      start_period: "10"

  target2:
    image: hmlio/vaas-cve-2014-6271 # shellshock
    # ports:
    #   - 8082:80
    healthcheck:
      test: "curl -f localhost:80"
      interval: 5s
      retries: 3

  target3:
    image: penkit/vsftpd:2.3.4 # vsftpd backdoor, do not trust this image

  wordpress:
    image: vulhub/wordpress:4.6
    depends_on:
     - wordpress-mysql
    environment: 
     - WORDPRESS_DB_HOST=wordpress-mysql:3306
     - WORDPRESS_DB_USER=root
     - WORDPRESS_DB_PASSWORD=root
     - WORDPRESS_DB_NAME=wordpress
    ports:
     - "8080:80"
    links:
      - wordpress-mysql
    # unix/webapp/wp_phpmailer_host_header
    # set RHOSTS wordpress
    # cat /var/www/html/wp-config.php
    # fail: execute -f /bin/grep -a DB_PASSWORD /var/www/html/wp-config.php


  wordpress-mysql:
    image: mysql:5
    environment: 
     - MYSQL_ROOT_PASSWORD=root