version: "3.7"

services:

  db:
    image: postgres:12-alpine
    env_file:
      - env/.env.db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres/data/

volumes:
  postgres_data:

