---

description: |
  This campaign focuses on a faulty version of wordpress.
  The wordpress server needs to be installed and running!

  This campaign does not contain any precondition, as it
  is meant for demonstration purposses
adversary: hacker
schema:
  reconnaissance:
    flag: 10.5.0.6
    techniques: all
  exploitation:
    flag: Meterpreter session
    techniques: all
  post:
    flag: mysql://root:root@wordpress-mysql:3306/wordpress
    techniques: all
